feat: #15 Enhancing services list display
microcks/microcks-docker-desktop-extension pull request #16
Opened 2023-05-15 15:25 UTC by lbroudoux

### Description

- API style/type is rendered as in the Web UI (at least using the same colors)
- URL is built correctly (with `/rest`, `/graph`, `/soap` or `/dynarest` path prefix and using the specific GRPC port)
- Method color is aligned on the Web UI
- A link to details should be added next to the version of the API.

![Capture d’écran 2023-05-15 à 17 19 22](https://github.com/microcks/microcks-docker-desktop-extension/assets/1538635/2394598c-1a85-445a-840f-716da0e94288)

### Related issue(s)

Resolves #15

2023-05-15 22:33 UTC, hguerrero requested changes

2023-05-15 22:33 UTC, hguerrero commented on client/src/components/lib/ServiceType.tsx
Do you know if we intend to add many more components to this folder? If not, I'd keep it in components (an already-existing "lib" subdirectory).

2023-05-16 20:33 UTC, hguerrero commented on client/src/components/lib/ServiceType.tsx
I suggest we keep it with the current `components`, and let's revisit it if we notice we added more _components_ that are not main sections.

2023-05-17 14:42 UTC, lbroudoux commented on client/src/components/lib/ServiceType.tsx
Removed the `/lib` folder in new commit.

2023-05-19 14:08 UTC, merged